services:
  scotch-egg:
    build: .
    container_name: scotch-egg
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m" # Caps log file size to 10MB to protect the SD Card
        max-file: "3"   # Keeps only the last 3 log files